# CESSDA CVS User Guide Documentation
---
title: CESSDA Vocabulary Service User Guide
baseurl: /documentation/
logo: cessda_logo_cvs.png
color_scheme: cessda
serviceurl: /
destination: ./_site/documentation

# Theme
theme: jekyll-cessda-docs
search_enabled: true

defaults:
 -
  scope:
   path: "**/*.md"
   type: "pages"
  values:
   permalink: /:path/:basename:output_ext
   layout: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Dockerfile
  - Jenkinsfile
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - nginx/
  - node_modules/
  - README.md
  - CONTRIBUTORS.md
  - CHANGELOG.md
  - document-navigation-structure.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scripts/
